### ISSUE TITLE
Remove manual steps when adding new databases

### ISSUE THREAD

**Issue by dbeatty10** [dbeatty10/dbt-teradata#13]
### Describe the feature
Remove any manual steps necessary to automatically add and use a new database for materializing tables, views, etc.

### Describe alternatives you've considered
- somehow remove the need for the "drop relation if it exists" stored procedure
- create this stored procedure manually when creating a new database

### Additional context
The way this adapter is built so far, each database requires a stored procedure named `dbt_drop_relation_if_exists`. This stored proc is not created automatically when a new database is created; it needs to be created manually.

Creating a new database is a 3 step process:
1. Create the new database (`CREATE DATABASE ...`)
1. Grant permissions to create stored procedures (`GRANT CREATE PROCEDURE ON ...`)
1. Create the stored procedure (`REPLACE PROCEDURE ...`)

### Who will this benefit?
Automatically creating this stored procedure would be useful for fully automated integration testing. It would also reduce the barriers to entry for new or seasoned users that need/want to create brand-new databases.

**Comment by adamtwo** [comment]
Now that PR #5 is merged, we no longer need dbt_drop_relation_if_exists procedure. I think we can close this issue when a new version of the adapter is released.

**Comment by dbeatty10** [comment]
New version released to PyPI today that resolves this issue.
