### ISSUE TITLE
Missing dbt_drop_relation_if_exists stored procedure definition

### ISSUE THREAD

**Issue by adamtwo** [dbeatty10/dbt-teradata#3]
### Describe the bug
The adapter relies on `dbt_drop_relation_if_exists` stored procedure. I could not find it anywhere in the source code.

### Steps To Reproduce
1. Generate a sample dbt project:
    ```
    dbt init teradata
    ```
1. Run the project:
    ```
    dbt run
    ```

### Expected behavior
I expected dbt to finish successfully.

### Screenshots and log output
dbt failed with:
```
Database Error in model total_cpu_consumption (models/total_cpu_consumption.sql)
  [Version 17.10.0.2] [Session 47779937] [Teradata Database] [Error 5495] Stored Procedure  'db.dbt_drop_relation_if_exists' does not exist.
   at gosqldriver/teradatasql.(*teradataConnection).formatDatabaseError TeradataConnection.go:1142
   at gosqldriver/teradatasql.(*teradataConnection).makeChainedDatabaseError TeradataConnection.go:1158
   at gosqldriver/teradatasql.(*teradataConnection).processErrorParcel TeradataConnection.go:1232
   at gosqldriver/teradatasql.(*TeradataRows).processResponseBundle TeradataRows.go:2112
   at gosqldriver/teradatasql.(*TeradataRows).executeSQLRequest TeradataRows.go:794
   at gosqldriver/teradatasql.newTeradataRows TeradataRows.go:653
   at gosqldriver/teradatasql.(*teradataStatement).QueryContext TeradataStatement.go:122
   at gosqldriver/teradatasql.(*teradataConnection).QueryContext TeradataConnection.go:2113
   at database/sql.ctxDriverQuery ctxutil.go:48
   at database/sql.(*DB).queryDC.func1 sql.go:1579
   at database/sql.withLock sql.go:3204
   at database/sql.(*DB).queryDC sql.go:1574
   at database/sql.(*Conn).QueryContext sql.go:1823
   at main.goCreateRows goside.go:652
   at main._cgoexpwrap_683a201b0f95_goCreateRows _cgo_gotypes.go:363
   at runtime.cgocallbackg1 cgocall.go:332
   at runtime.cgocallbackg cgocall.go:207
   at runtime.cgocallback_gofunc asm_amd64.s:793
   at runtime.goexit asm_amd64.s:1373
  compiled SQL at target/compiled/teradata/models/total_cpu_consumption.sql
```

**The output of `dbt --version`:**
```
installed version: 0.19.0
   latest version: 0.21.0

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - teradata: 0.19.0a
```

**The operating system you're using:**
MacOS

**The output of `python --version`:**
Python 3.9.8

### Additional context
I figured the stored procedure is needed because Teradata doesn't provide `IF EXISTS` conditional for `DROP` statement. 

I was able to get it to work with the following stored procedure. Do we need to add it to the documentation?

```
CREATE PROCEDURE dbt_drop_relation_if_exists( 
   IN in_relationship_type VARCHAR(25), 
   IN in_relationship_name VARCHAR(100) 
) 
BEGIN
	DECLARE sqlstr varchar(500);
	DECLARE exit handler for sqlstate '42000' begin end;
	SET sqlstr = 'DROP ' || in_relationship_type || ' ' || in_relationship_name;
	execute immediate sqlstr;
END;    
```

**Comment by dbeatty10** [comment]
@adamtwo ,
Added this definition here: https://github.com/dbeatty10/dbt-teradata/blob/dev/0.19.0/script/dbt_drop_relation_if_exists.sql

However, we should probably have this included within the install instructions (which don't exist yet). Will leave this issue open until install instructions are created that include this script.

**Comment by adamtwo** [comment]
Good deal! 

On a related note, I've an idea how to modify the macros so that they don't require stored procedures. I'll need to play with it a bit. I'll let you know if it worked.

**Comment by adamtwo** [comment]
With PR https://github.com/dbeatty10/dbt-teradata/pull/5, we no longer need `dbt_drop_relation_if_exists` procedure. I think we can close this issue when a new version of the adapter is released.

**Comment by dbeatty10** [comment]
New version released to PyPI today that resolves this issue.
